project_id = "lysajjlxfgpbcsyaqjyu"

[functions.prepare-automation]
verify_jwt = false

[functions.automation-webhook]
verify_jwt = false

[functions.enrich-test-script]
verify_jwt = false

[functions.heal-automation]
verify_jwt = false