import { useState, useEffect } from "react";
import { useNavigate } from "react-router-dom";
import { ArrowLeft, Loader2, Bug } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from "@/components/ui/select";
import { Label } from "@/components/ui/label";
import { useToast } from "@/hooks/use-toast";
import { useAuth } from "@/contexts/AuthContext";
import { supabase } from "@/integrations/supabase/client";
import type { BugSeverity } from "@/types/bugs";
import type { Feature } from "@/types/qa";

export default function CreateBug() {
  const navigate = useNavigate();
  const { user } = useAuth();
  const { toast } = useToast();
  const [loading, setLoading] = useState(false);
  const [features, setFeatures] = useState<Feature[]>([]);
  
  const [formData, setFormData] = useState({
    title: "",
    description: "",
    severity: "minor" as BugSeverity,
    feature_id: "",
    steps_to_reproduce: [""],
    expected_behavior: "",
    actual_behavior: "",
    environment: "",
  });

  useEffect(() => {
    loadFeatures();
  }, []);

  const loadFeatures = async () => {
    const { data } = await supabase
      .from("features")
      .select("*")
      .order("order_index");
    setFeatures((data || []) as Feature[]);
  };

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    if (!user) return;

    if (!formData.title.trim()) {
      toast({ variant: "destructive", title: "Title is required" });
      return;
    }

    setLoading(true);
    try {
      const { error } = await supabase.from("bugs").insert({
        bug_code: "TEMP", // Will be auto-generated by trigger
        title: formData.title,
        description: formData.description || null,
        severity: formData.severity,
        feature_id: formData.feature_id || null,
        steps_to_reproduce: formData.steps_to_reproduce.filter(s => s.trim()),
        expected_behavior: formData.expected_behavior || null,
        actual_behavior: formData.actual_behavior || null,
        environment: formData.environment || null,
        reported_by: user.id,
        status: "open",
      } as any);

      if (error) throw error;

      toast({ title: "Bug reported successfully" });
      navigate("/bugs");
    } catch (error: any) {
      console.error("Error creating bug:", error);
      toast({ variant: "destructive", title: "Error", description: error.message });
    } finally {
      setLoading(false);
    }
  };

  const addStep = () => {
    setFormData(prev => ({
      ...prev,
      steps_to_reproduce: [...prev.steps_to_reproduce, ""],
    }));
  };

  const updateStep = (index: number, value: string) => {
    setFormData(prev => ({
      ...prev,
      steps_to_reproduce: prev.steps_to_reproduce.map((s, i) => i === index ? value : s),
    }));
  };

  const removeStep = (index: number) => {
    setFormData(prev => ({
      ...prev,
      steps_to_reproduce: prev.steps_to_reproduce.filter((_, i) => i !== index),
    }));
  };

  return (
    <div className="space-y-6 max-w-2xl mx-auto">
      <div className="flex items-center gap-4">
        <Button variant="ghost" size="icon" onClick={() => navigate("/bugs")}>
          <ArrowLeft className="h-5 w-5" />
        </Button>
        <div>
          <h1 className="text-2xl font-bold text-foreground">Report Bug</h1>
          <p className="text-muted-foreground">Document a new issue</p>
        </div>
      </div>

      <form onSubmit={handleSubmit} className="space-y-6">
        <Card className="glass">
          <CardHeader>
            <CardTitle className="flex items-center gap-2">
              <Bug className="h-5 w-5 text-primary" />
              Bug Details
            </CardTitle>
          </CardHeader>
          <CardContent className="space-y-4">
            <div>
              <Label htmlFor="title">Title *</Label>
              <Input
                id="title"
                value={formData.title}
                onChange={(e) => setFormData(prev => ({ ...prev, title: e.target.value }))}
                placeholder="Brief description of the bug"
              />
            </div>

            <div className="grid grid-cols-2 gap-4">
              <div>
                <Label>Severity *</Label>
                <Select
                  value={formData.severity}
                  onValueChange={(v) => setFormData(prev => ({ ...prev, severity: v as BugSeverity }))}
                >
                  <SelectTrigger>
                    <SelectValue />
                  </SelectTrigger>
                  <SelectContent>
                    <SelectItem value="critical">Critical</SelectItem>
                    <SelectItem value="major">Major</SelectItem>
                    <SelectItem value="minor">Minor</SelectItem>
                    <SelectItem value="trivial">Trivial</SelectItem>
                  </SelectContent>
                </Select>
              </div>
              <div>
                <Label>Feature</Label>
                <Select
                  value={formData.feature_id}
                  onValueChange={(v) => setFormData(prev => ({ ...prev, feature_id: v }))}
                >
                  <SelectTrigger>
                    <SelectValue placeholder="Select feature" />
                  </SelectTrigger>
                  <SelectContent>
                    {features.map(f => (
                      <SelectItem key={f.id} value={f.id}>{f.name}</SelectItem>
                    ))}
                  </SelectContent>
                </Select>
              </div>
            </div>

            <div>
              <Label htmlFor="description">Description</Label>
              <Textarea
                id="description"
                value={formData.description}
                onChange={(e) => setFormData(prev => ({ ...prev, description: e.target.value }))}
                placeholder="Detailed description of the bug"
                rows={3}
              />
            </div>

            <div>
              <Label>Steps to Reproduce</Label>
              <div className="space-y-2">
                {formData.steps_to_reproduce.map((step, index) => (
                  <div key={index} className="flex gap-2">
                    <span className="text-sm text-muted-foreground w-6 pt-2">{index + 1}.</span>
                    <Input
                      value={step}
                      onChange={(e) => updateStep(index, e.target.value)}
                      placeholder={`Step ${index + 1}`}
                    />
                    {formData.steps_to_reproduce.length > 1 && (
                      <Button type="button" variant="ghost" size="sm" onClick={() => removeStep(index)}>
                        ×
                      </Button>
                    )}
                  </div>
                ))}
                <Button type="button" variant="outline" size="sm" onClick={addStep}>
                  + Add Step
                </Button>
              </div>
            </div>

            <div>
              <Label htmlFor="expected">Expected Behavior</Label>
              <Textarea
                id="expected"
                value={formData.expected_behavior}
                onChange={(e) => setFormData(prev => ({ ...prev, expected_behavior: e.target.value }))}
                placeholder="What should happen?"
                rows={2}
              />
            </div>

            <div>
              <Label htmlFor="actual">Actual Behavior</Label>
              <Textarea
                id="actual"
                value={formData.actual_behavior}
                onChange={(e) => setFormData(prev => ({ ...prev, actual_behavior: e.target.value }))}
                placeholder="What actually happened?"
                rows={2}
              />
            </div>

            <div>
              <Label htmlFor="environment">Environment</Label>
              <Input
                id="environment"
                value={formData.environment}
                onChange={(e) => setFormData(prev => ({ ...prev, environment: e.target.value }))}
                placeholder="e.g., Chrome 120, Windows 11, Production"
              />
            </div>
          </CardContent>
        </Card>

        <div className="flex gap-3 justify-end">
          <Button type="button" variant="outline" onClick={() => navigate("/bugs")}>
            Cancel
          </Button>
          <Button type="submit" disabled={loading}>
            {loading ? <Loader2 className="h-4 w-4 animate-spin mr-2" /> : null}
            Report Bug
          </Button>
        </div>
      </form>
    </div>
  );
}
