import { useState } from "react";
import { useNavigate } from "react-router-dom";
import { ArrowLeft, ArrowRight, Save, Loader2 } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { Card, CardContent } from "@/components/ui/card";
import { Label } from "@/components/ui/label";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Badge } from "@/components/ui/badge";
import { useToast } from "@/hooks/use-toast";
import { useAuth } from "@/contexts/AuthContext";
import { useProject } from "@/contexts/ProjectContext";
import { supabase } from "@/integrations/supabase/client";
import { CycleGroupEditor } from "@/components/qa/cycles/CycleGroupEditor";
import { CycleContextPanel } from "@/components/qa/cycles/CycleContextPanel";
import { PriorityBadge } from "@/components/qa/badges";
import { cn } from "@/lib/utils";
import type { PriorityLevel } from "@/types/qa";
import type { CreateCycleGroupForm } from "@/types/cycle";

const STEPS = ["Metadata", "Context", "Scenarios", "Review"];

export default function CreateCycle() {
  const navigate = useNavigate();
  const { toast } = useToast();
  const { user } = useAuth();
  const { currentProject } = useProject();
  const [currentStep, setCurrentStep] = useState(0);
  const [saving, setSaving] = useState(false);

  // Form state
  const [name, setName] = useState("");
  const [priority, setPriority] = useState<PriorityLevel>("medium");
  const [description, setDescription] = useState("");
  const [groups, setGroups] = useState<CreateCycleGroupForm[]>([
    { name: "", description: "", order_index: 0, scenarios: [{ scenario_code: "A1", title: "", description: "", order_index: 0, has_steps: false, steps: [] }] },
  ]);

  const validateStep = (step: number): boolean => {
    switch (step) {
      case 0: return name.trim().length > 0;
      case 1: return true; // description is optional
      case 2:
        return groups.length > 0 && groups.every(g =>
          g.name.trim().length > 0 &&
          g.scenarios.length > 0 &&
          g.scenarios.every(s => s.title.trim().length > 0)
        );
      default: return true;
    }
  };

  const handleSave = async () => {
    if (!user || !currentProject) return;
    try {
      setSaving(true);

      // 1. Create cycle
      const { data: cycle, error: cycleError } = await supabase
        .from("test_cycles")
        .insert({
          name,
          description: description || null,
          priority,
          project_id: currentProject.id,
          created_by: user.id,
          cycle_code: "", // auto-generated by trigger
          status: "active" as any,
        })
        .select()
        .single();
      if (cycleError) throw cycleError;

      // 2. Create groups + scenarios
      for (let gIdx = 0; gIdx < groups.length; gIdx++) {
        const group = groups[gIdx];
        const { data: createdGroup, error: groupError } = await supabase
          .from("cycle_groups")
          .insert({
            cycle_id: cycle.id,
            name: group.name,
            description: group.description || null,
            order_index: gIdx,
          })
          .select()
          .single();
        if (groupError) throw groupError;

        // Insert scenarios
        if (group.scenarios.length > 0) {
          const { error: scenarioError } = await supabase
            .from("cycle_scenarios")
            .insert(
              group.scenarios.map((s, sIdx) => ({
                group_id: createdGroup.id,
                scenario_code: s.scenario_code,
                title: s.title,
                description: s.description || null,
                order_index: sIdx,
                has_steps: s.has_steps,
                steps: s.has_steps && s.steps.length > 0 ? s.steps : null,
              }))
            );
          if (scenarioError) throw scenarioError;
        }
      }

      toast({ title: "Cycle created", description: `${cycle.cycle_code} — ${name}` });
      navigate(`/qa/cycles/${cycle.id}`);
    } catch (error: any) {
      console.error("Error creating cycle:", error);
      toast({ title: "Error creating cycle", description: error.message, variant: "destructive" });
    } finally {
      setSaving(false);
    }
  };

  const totalScenarios = groups.reduce((sum, g) => sum + g.scenarios.length, 0);

  return (
    <div className="space-y-4 sm:space-y-6">
      {/* Header */}
      <div className="flex items-center gap-3">
        <Button variant="ghost" size="icon" onClick={() => navigate(-1)} className="flex-shrink-0">
          <ArrowLeft className="h-5 w-5" />
        </Button>
        <div className="flex-1 min-w-0">
          <h1 className="text-xl sm:text-2xl font-bold text-foreground">Create Test Cycle</h1>
          <p className="text-sm text-muted-foreground">Step {currentStep + 1} of {STEPS.length}</p>
        </div>
      </div>

      {/* Stepper */}
      <div className="flex gap-1 sm:gap-2">
        {STEPS.map((label, i) => (
          <button
            key={label}
            onClick={() => i < currentStep && setCurrentStep(i)}
            className={cn(
              "flex-1 h-1.5 sm:h-2 rounded-full transition-colors",
              i <= currentStep ? "bg-primary" : "bg-muted",
              i < currentStep && "cursor-pointer hover:bg-primary/80"
            )}
          />
        ))}
      </div>
      <div className="flex justify-between text-xs text-muted-foreground px-0.5">
        {STEPS.map((label, i) => (
          <span key={label} className={cn(i === currentStep && "text-primary font-medium")}>
            {label}
          </span>
        ))}
      </div>

      {/* Step content */}
      <Card>
        <CardContent className="p-4 sm:p-6">
          {/* Step 0: Metadata */}
          {currentStep === 0 && (
            <div className="space-y-4">
              <div>
                <Label>Cycle Name *</Label>
                <Input
                  placeholder="e.g., Batch & Teacher Configuration Cycle"
                  value={name}
                  onChange={(e) => setName(e.target.value)}
                  className="mt-1.5"
                />
              </div>
              <div>
                <Label>Priority</Label>
                <Select value={priority} onValueChange={(v) => setPriority(v as PriorityLevel)}>
                  <SelectTrigger className="mt-1.5">
                    <SelectValue />
                  </SelectTrigger>
                  <SelectContent>
                    {(["critical", "high", "medium", "low"] as PriorityLevel[]).map((p) => (
                      <SelectItem key={p} value={p} className="capitalize">{p}</SelectItem>
                    ))}
                  </SelectContent>
                </Select>
              </div>
            </div>
          )}

          {/* Step 1: Context */}
          {currentStep === 1 && (
            <div className="space-y-4">
              <div>
                <Label>Context & Theory</Label>
                <p className="text-xs text-muted-foreground mt-0.5 mb-2">
                  Explain the feature, relationships, hierarchy, and rules testers need to understand before starting.
                </p>
                <Textarea
                  placeholder="Describe the feature being tested, how components relate to each other, what the tester needs to know before starting..."
                  value={description}
                  onChange={(e) => setDescription(e.target.value)}
                  rows={12}
                  className="resize-y"
                />
              </div>
            </div>
          )}

          {/* Step 2: Scenarios */}
          {currentStep === 2 && (
            <div className="space-y-4">
              <div className="flex items-center justify-between">
                <div>
                  <Label className="text-base font-semibold">Scenario Groups</Label>
                  <p className="text-xs text-muted-foreground mt-0.5">
                    Organize scenarios into logical groups (A, B, C...). Each scenario is plain language — no mandatory steps.
                  </p>
                </div>
                <Badge variant="secondary" className="font-mono">
                  {groups.length} group{groups.length !== 1 ? "s" : ""} · {totalScenarios} scenario{totalScenarios !== 1 ? "s" : ""}
                </Badge>
              </div>
              <CycleGroupEditor groups={groups} setGroups={setGroups} />
            </div>
          )}

          {/* Step 3: Review */}
          {currentStep === 3 && (
            <div className="space-y-4">
              <h3 className="font-semibold text-foreground">Review Cycle</h3>
              <div className="grid gap-3 sm:grid-cols-2">
                <div>
                  <span className="text-xs text-muted-foreground">Name</span>
                  <p className="font-medium">{name}</p>
                </div>
                <div>
                  <span className="text-xs text-muted-foreground">Priority</span>
                  <div className="mt-0.5"><PriorityBadge priority={priority} /></div>
                </div>
                <div>
                  <span className="text-xs text-muted-foreground">Groups</span>
                  <p className="font-medium">{groups.length}</p>
                </div>
                <div>
                  <span className="text-xs text-muted-foreground">Total Scenarios</span>
                  <p className="font-medium">{totalScenarios}</p>
                </div>
              </div>

              {description && (
                <CycleContextPanel content={description} defaultExpanded={false} />
              )}

              <div className="space-y-2">
                <Label className="text-xs font-semibold">Scenario Overview</Label>
                {groups.map((g, gIdx) => (
                  <div key={gIdx} className="border rounded-lg p-3">
                    <div className="flex items-center gap-2 mb-2">
                      <Badge variant="outline" className="font-mono text-[10px]">
                        Group {String.fromCharCode(65 + gIdx)}
                      </Badge>
                      <span className="font-medium text-sm">{g.name}</span>
                    </div>
                    <ul className="space-y-1 pl-2">
                      {g.scenarios.map((s, sIdx) => (
                        <li key={sIdx} className="text-sm text-muted-foreground flex items-start gap-2">
                          <span className="font-mono text-[10px] text-primary mt-0.5">{s.scenario_code}</span>
                          <span>{s.title || "Untitled"}</span>
                        </li>
                      ))}
                    </ul>
                  </div>
                ))}
              </div>
            </div>
          )}
        </CardContent>
      </Card>

      {/* Navigation */}
      <div className="flex justify-between">
        <Button
          variant="outline"
          onClick={() => setCurrentStep((prev) => prev - 1)}
          disabled={currentStep === 0}
        >
          <ArrowLeft className="h-4 w-4 mr-1.5" /> Previous
        </Button>
        {currentStep < STEPS.length - 1 ? (
          <Button
            onClick={() => setCurrentStep((prev) => prev + 1)}
            disabled={!validateStep(currentStep)}
          >
            Next <ArrowRight className="h-4 w-4 ml-1.5" />
          </Button>
        ) : (
          <Button onClick={handleSave} disabled={saving || !validateStep(2)}>
            {saving ? <Loader2 className="h-4 w-4 mr-1.5 animate-spin" /> : <Save className="h-4 w-4 mr-1.5" />}
            Create Cycle
          </Button>
        )}
      </div>
    </div>
  );
}
