// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.23.0";

// src/lib/mcp/tools/list-projects.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.23.0";

// src/lib/mcp/shared/supabase.ts
import { createClient } from "npm:@supabase/supabase-js@^2.91.1";
function getSupabaseForUser(ctx) {
  const url = process.env.SUPABASE_URL;
  const anon = process.env.SUPABASE_PUBLISHABLE_KEY ?? process.env.SUPABASE_ANON_KEY;
  const token = ctx.getToken();
  return createClient(url, anon, {
    global: { headers: { Authorization: `Bearer ${token}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}

// src/lib/mcp/shared/auth.ts
async function requireAdmin(ctx) {
  if (!ctx.isAuthenticated || !ctx.isAuthenticated()) {
    return fail("Not authenticated. Sign in to this app to use MCP tools.");
  }
  const userId = ctx.getUserId?.();
  if (!userId) {
    return fail("Could not resolve user id from token.");
  }
  const supabase = getSupabaseForUser(ctx);
  const { data, error } = await supabase.rpc("has_role", {
    _user_id: userId,
    _role: "admin"
  });
  if (error) {
    return { ok: false, userId, error: err(`Failed to verify role: ${error.message}`) };
  }
  if (data !== true) {
    return {
      ok: false,
      userId,
      error: err("Admin role required. These MCP tools are restricted to platform admins.")
    };
  }
  return { ok: true, userId, error: err("") };
}
function err(message) {
  return { content: [{ type: "text", text: message }], isError: true };
}
function fail(message) {
  return { ok: false, userId: "", error: err(message) };
}
function jsonResult(data) {
  const text = JSON.stringify(data, null, 2);
  return {
    content: [{ type: "text", text }],
    structuredContent: data
  };
}

// src/lib/mcp/tools/list-projects.ts
var list_projects_default = defineTool({
  name: "list_projects",
  title: "List projects",
  description: "List all projects the admin can access, with id, name, and description.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    const guard = await requireAdmin(ctx);
    if (!guard.ok) return guard.error;
    const supabase = getSupabaseForUser(ctx);
    const { data, error } = await supabase.from("projects").select("id, name, description, created_at").order("created_at", { ascending: true });
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return jsonResult({ projects: data ?? [] });
  }
});

// src/lib/mcp/tools/list-cycles.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.23.0";
import { z } from "npm:zod@^3.25.76";
var list_cycles_default = defineTool2({
  name: "list_cycles",
  title: "List test cycles",
  description: "List test cycles in a project with progress counts (pass/fail/review/untested).",
  inputSchema: {
    project_id: z.string().uuid().describe("Project id from list_projects"),
    status: z.enum(["draft", "active", "archived"]).optional()
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ project_id, status }, ctx) => {
    const guard = await requireAdmin(ctx);
    if (!guard.ok) return guard.error;
    const supabase = getSupabaseForUser(ctx);
    let q = supabase.from("test_cycles").select("id, cycle_code, name, priority, status, created_at").eq("project_id", project_id).order("created_at", { ascending: false });
    if (status) q = q.eq("status", status);
    const { data: cycles, error } = await q;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    const results = await Promise.all(
      (cycles ?? []).map(async (c) => {
        const { data: groups } = await supabase.from("cycle_groups").select("id").eq("cycle_id", c.id);
        const groupIds = (groups ?? []).map((g) => g.id);
        let totalScenarios = 0;
        if (groupIds.length > 0) {
          const { count } = await supabase.from("cycle_scenarios").select("id", { count: "exact", head: true }).in("group_id", groupIds);
          totalScenarios = count ?? 0;
        }
        const { data: verdicts } = await supabase.from("cycle_scenario_verdicts").select("scenario_id, status").eq("cycle_id", c.id);
        const byScenario = {};
        (verdicts ?? []).forEach((v) => {
          byScenario[v.scenario_id] = v.status;
        });
        const values = Object.values(byScenario);
        return {
          ...c,
          total_scenarios: totalScenarios,
          verdicted: values.length,
          untested: Math.max(0, totalScenarios - values.length),
          pass: values.filter((s) => s === "pass").length,
          fail: values.filter((s) => s === "fail").length,
          review: values.filter((s) => s === "review").length
        };
      })
    );
    return jsonResult({ cycles: results });
  }
});

// src/lib/mcp/tools/get-cycle.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.23.0";
import { z as z2 } from "npm:zod@^3.25.76";
var get_cycle_default = defineTool3({
  name: "get_cycle",
  title: "Get a cycle",
  description: "Get one cycle with groups and scenarios. Each scenario includes the latest verdict (status, comment, tester, timestamp) if any.",
  inputSchema: {
    cycle_id: z2.string().uuid()
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ cycle_id }, ctx) => {
    const guard = await requireAdmin(ctx);
    if (!guard.ok) return guard.error;
    const supabase = getSupabaseForUser(ctx);
    const { data: cycle, error: cErr } = await supabase.from("test_cycles").select("id, cycle_code, name, description, priority, status, project_id, created_at").eq("id", cycle_id).maybeSingle();
    if (cErr) return { content: [{ type: "text", text: cErr.message }], isError: true };
    if (!cycle) return { content: [{ type: "text", text: "Cycle not found" }], isError: true };
    const { data: groups } = await supabase.from("cycle_groups").select("id, name, description, order_index").eq("cycle_id", cycle_id).order("order_index");
    const groupIds = (groups ?? []).map((g) => g.id);
    const { data: scenarios } = groupIds.length ? await supabase.from("cycle_scenarios").select("id, scenario_code, title, description, group_id, order_index").in("group_id", groupIds).order("order_index") : { data: [] };
    const { data: verdicts } = await supabase.from("cycle_scenario_verdicts").select("scenario_id, user_id, status, comment, created_at").eq("cycle_id", cycle_id).order("created_at", { ascending: false });
    const latestByScenario = /* @__PURE__ */ new Map();
    (verdicts ?? []).forEach((v) => {
      if (!latestByScenario.has(v.scenario_id)) latestByScenario.set(v.scenario_id, v);
    });
    const testerIds = Array.from(new Set((verdicts ?? []).map((v) => v.user_id)));
    const nameById = {};
    if (testerIds.length) {
      const { data: profs } = await supabase.from("profiles").select("user_id, full_name, email").in("user_id", testerIds);
      (profs ?? []).forEach((p) => {
        nameById[p.user_id] = p.full_name || p.email;
      });
    }
    const groupOut = (groups ?? []).map((g) => ({
      ...g,
      scenarios: (scenarios ?? []).filter((s) => s.group_id === g.id).map((s) => {
        const v = latestByScenario.get(s.id);
        return {
          ...s,
          latest_verdict: v ? {
            status: v.status,
            comment: v.comment,
            tester_id: v.user_id,
            tester_name: nameById[v.user_id] ?? null,
            created_at: v.created_at
          } : null
        };
      })
    }));
    return jsonResult({ cycle, groups: groupOut });
  }
});

// src/lib/mcp/tools/get-scenario-verdicts.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.23.0";
import { z as z3 } from "npm:zod@^3.25.76";
var get_scenario_verdicts_default = defineTool4({
  name: "get_scenario_verdicts",
  title: "Get scenario verdicts",
  description: "Full verdict history for one scenario in one cycle: all testers, all statuses, all comments. Use this to judge comment quality.",
  inputSchema: {
    cycle_id: z3.string().uuid(),
    scenario_id: z3.string().uuid()
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ cycle_id, scenario_id }, ctx) => {
    const guard = await requireAdmin(ctx);
    if (!guard.ok) return guard.error;
    const supabase = getSupabaseForUser(ctx);
    const { data: scenario } = await supabase.from("cycle_scenarios").select("id, scenario_code, title, description").eq("id", scenario_id).maybeSingle();
    const { data: verdicts, error } = await supabase.from("cycle_scenario_verdicts").select("id, user_id, status, comment, created_at").eq("cycle_id", cycle_id).eq("scenario_id", scenario_id).order("created_at", { ascending: false });
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    const testerIds = Array.from(new Set((verdicts ?? []).map((v) => v.user_id)));
    const nameById = {};
    if (testerIds.length) {
      const { data: profs } = await supabase.from("profiles").select("user_id, full_name, email").in("user_id", testerIds);
      (profs ?? []).forEach((p) => {
        nameById[p.user_id] = p.full_name || p.email;
      });
    }
    const enriched = (verdicts ?? []).map((v) => ({
      ...v,
      tester_name: nameById[v.user_id] ?? null
    }));
    return jsonResult({ scenario, verdicts: enriched });
  }
});

// src/lib/mcp/tools/list-pending-scenarios.ts
import { defineTool as defineTool5 } from "npm:@lovable.dev/mcp-js@0.23.0";
import { z as z4 } from "npm:zod@^3.25.76";
var list_pending_scenarios_default = defineTool5({
  name: "list_pending_scenarios",
  title: "List pending scenarios",
  description: "Scenarios in active cycles for a project that have no verdict yet. Optionally filter by tester (returns scenarios the tester specifically has not verdicted).",
  inputSchema: {
    project_id: z4.string().uuid(),
    tester_id: z4.string().uuid().optional(),
    cycle_id: z4.string().uuid().optional()
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ project_id, tester_id, cycle_id }, ctx) => {
    const guard = await requireAdmin(ctx);
    if (!guard.ok) return guard.error;
    const supabase = getSupabaseForUser(ctx);
    let cyclesQ = supabase.from("test_cycles").select("id, cycle_code, name, priority").eq("project_id", project_id).eq("status", "active");
    if (cycle_id) cyclesQ = cyclesQ.eq("id", cycle_id);
    const { data: cycles } = await cyclesQ;
    if (!cycles?.length) return jsonResult({ pending: [] });
    const cycleIds = cycles.map((c) => c.id);
    const cycleMap = Object.fromEntries(cycles.map((c) => [c.id, c]));
    const { data: groups } = await supabase.from("cycle_groups").select("id, cycle_id").in("cycle_id", cycleIds);
    if (!groups?.length) return jsonResult({ pending: [] });
    const gToC = {};
    groups.forEach((g) => gToC[g.id] = g.cycle_id);
    const { data: scenarios } = await supabase.from("cycle_scenarios").select("id, scenario_code, title, group_id").in(
      "group_id",
      groups.map((g) => g.id)
    );
    let verdictQ = supabase.from("cycle_scenario_verdicts").select("scenario_id, user_id").in("cycle_id", cycleIds);
    if (tester_id) verdictQ = verdictQ.eq("user_id", tester_id);
    const { data: verdicts } = await verdictQ;
    const verdictedIds = new Set((verdicts ?? []).map((v) => v.scenario_id));
    const priorityOrder = {
      critical: 0,
      high: 1,
      medium: 2,
      low: 3
    };
    const pending = (scenarios ?? []).filter((s) => !verdictedIds.has(s.id)).map((s) => {
      const cid = gToC[s.group_id];
      const c = cycleMap[cid];
      return {
        scenario_id: s.id,
        scenario_code: s.scenario_code,
        title: s.title,
        cycle_id: cid,
        cycle_code: c?.cycle_code,
        cycle_name: c?.name,
        cycle_priority: c?.priority
      };
    }).sort(
      (a, b) => (priorityOrder[a.cycle_priority ?? "low"] ?? 4) - (priorityOrder[b.cycle_priority ?? "low"] ?? 4)
    );
    return jsonResult({ pending, count: pending.length });
  }
});

// src/lib/mcp/tools/get-tester-activity.ts
import { defineTool as defineTool6 } from "npm:@lovable.dev/mcp-js@0.23.0";
import { z as z5 } from "npm:zod@^3.25.76";
var get_tester_activity_default = defineTool6({
  name: "get_tester_activity",
  title: "Get tester activity",
  description: "Per-tester day-wise activity within a date range: scenarios verdicted, bugs raised, timesheet entries. If tester_id omitted, returns activity for all testers in the project.",
  inputSchema: {
    project_id: z5.string().uuid(),
    from_date: z5.string().describe("ISO date, e.g. 2026-07-01"),
    to_date: z5.string().describe("ISO date, inclusive"),
    tester_id: z5.string().uuid().optional()
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ project_id, from_date, to_date, tester_id }, ctx) => {
    const guard = await requireAdmin(ctx);
    if (!guard.ok) return guard.error;
    const supabase = getSupabaseForUser(ctx);
    const fromISO = new Date(from_date).toISOString();
    const toISO = new Date(new Date(to_date).getTime() + 24 * 60 * 60 * 1e3 - 1).toISOString();
    const { data: cycles } = await supabase.from("test_cycles").select("id").eq("project_id", project_id);
    const cycleIds = (cycles ?? []).map((c) => c.id);
    let vQ = supabase.from("cycle_scenario_verdicts").select("user_id, status, comment, created_at, scenario_id, cycle_id").gte("created_at", fromISO).lte("created_at", toISO);
    if (cycleIds.length) vQ = vQ.in("cycle_id", cycleIds);
    if (tester_id) vQ = vQ.eq("user_id", tester_id);
    const { data: verdicts } = await vQ;
    let bQ = supabase.from("bugs").select("id, bug_code, created_by, created_at, status").eq("project_id", project_id).gte("created_at", fromISO).lte("created_at", toISO);
    if (tester_id) bQ = bQ.eq("created_by", tester_id);
    const { data: bugs } = await bQ;
    let tQ = supabase.from("qa_timesheets").select("user_id, work_date, bug_ids, content_items, summary").eq("project_id", project_id).gte("work_date", from_date).lte("work_date", to_date);
    if (tester_id) tQ = tQ.eq("user_id", tester_id);
    const { data: timesheets } = await tQ;
    const key = (u, d) => `${u}|${d}`;
    const buckets = /* @__PURE__ */ new Map();
    const ensure = (u, d) => {
      const k = key(u, d);
      let b = buckets.get(k);
      if (!b) {
        b = {
          tester_id: u,
          date: d,
          verdicts_total: 0,
          pass: 0,
          fail: 0,
          review: 0,
          bugs_raised: 0,
          timesheet: null
        };
        buckets.set(k, b);
      }
      return b;
    };
    (verdicts ?? []).forEach((v) => {
      const d = v.created_at.slice(0, 10);
      const b = ensure(v.user_id, d);
      b.verdicts_total += 1;
      if (v.status === "pass") b.pass += 1;
      else if (v.status === "fail") b.fail += 1;
      else if (v.status === "review") b.review += 1;
    });
    (bugs ?? []).forEach((bug) => {
      if (!bug.created_by) return;
      const d = bug.created_at.slice(0, 10);
      ensure(bug.created_by, d).bugs_raised += 1;
    });
    (timesheets ?? []).forEach((t) => {
      const b = ensure(t.user_id, t.work_date);
      const bugCount = Array.isArray(t.bug_ids) ? t.bug_ids.length : 0;
      const contentCount = Array.isArray(t.content_items) ? t.content_items.length : 0;
      b.timesheet = {
        bugs: bugCount,
        content_items: contentCount,
        has_summary: !!(t.summary && t.summary.trim())
      };
    });
    const userIds = Array.from(new Set(Array.from(buckets.values()).map((b) => b.tester_id)));
    const nameById = {};
    if (userIds.length) {
      const { data: profs } = await supabase.from("profiles").select("user_id, full_name, email").in("user_id", userIds);
      (profs ?? []).forEach((p) => nameById[p.user_id] = p.full_name || p.email);
    }
    const rows = Array.from(buckets.values()).map((b) => ({ ...b, tester_name: nameById[b.tester_id] ?? null })).sort((a, b) => a.date < b.date ? 1 : a.date > b.date ? -1 : 0);
    return jsonResult({
      range: { from: from_date, to: to_date },
      activity: rows
    });
  }
});

// src/lib/mcp/tools/list-bugs.ts
import { defineTool as defineTool7 } from "npm:@lovable.dev/mcp-js@0.23.0";
import { z as z6 } from "npm:zod@^3.25.76";
var list_bugs_default = defineTool7({
  name: "list_bugs",
  title: "List bugs",
  description: "List bugs with filters. Returns bug_code, title, priority, status, fix_status, assignee, and timestamps.",
  inputSchema: {
    project_id: z6.string().uuid().optional(),
    status: z6.string().optional(),
    fix_status: z6.string().optional(),
    assigned_to: z6.string().uuid().optional(),
    created_by: z6.string().uuid().optional(),
    login_type: z6.string().optional(),
    from_date: z6.string().optional(),
    to_date: z6.string().optional(),
    limit: z6.number().int().min(1).max(200).optional()
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (input, ctx) => {
    const guard = await requireAdmin(ctx);
    if (!guard.ok) return guard.error;
    const supabase = getSupabaseForUser(ctx);
    let q = supabase.from("bugs").select(
      "id, bug_code, title, priority, status, fix_status, login_type, assigned_to, created_by, created_at, updated_at, due_date, sla_status, reopen_count"
    ).order("created_at", { ascending: false }).limit(input.limit ?? 50);
    if (input.project_id) q = q.eq("project_id", input.project_id);
    if (input.status) q = q.eq("status", input.status);
    if (input.fix_status) q = q.eq("fix_status", input.fix_status);
    if (input.assigned_to) q = q.eq("assigned_to", input.assigned_to);
    if (input.created_by) q = q.eq("created_by", input.created_by);
    if (input.login_type) q = q.eq("login_type", input.login_type);
    if (input.from_date) q = q.gte("created_at", new Date(input.from_date).toISOString());
    if (input.to_date)
      q = q.lte(
        "created_at",
        new Date(new Date(input.to_date).getTime() + 24 * 60 * 60 * 1e3 - 1).toISOString()
      );
    const { data, error } = await q;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return jsonResult({ bugs: data ?? [], count: data?.length ?? 0 });
  }
});

// src/lib/mcp/tools/get-bug.ts
import { defineTool as defineTool8 } from "npm:@lovable.dev/mcp-js@0.23.0";
import { z as z7 } from "npm:zod@^3.25.76";
var get_bug_default = defineTool8({
  name: "get_bug",
  title: "Get a bug",
  description: "Get full detail for one bug including description, comments, history, attachment URLs, and reopen count. Accepts either the bug_code (e.g. BUG-405) or the id.",
  inputSchema: {
    bug_code: z7.string().optional(),
    bug_id: z7.string().uuid().optional()
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ bug_code, bug_id }, ctx) => {
    const guard = await requireAdmin(ctx);
    if (!guard.ok) return guard.error;
    if (!bug_code && !bug_id)
      return { content: [{ type: "text", text: "Provide bug_code or bug_id" }], isError: true };
    const supabase = getSupabaseForUser(ctx);
    let q = supabase.from("bugs").select("*");
    q = bug_id ? q.eq("id", bug_id) : q.eq("bug_code", bug_code.toUpperCase());
    const { data: bug, error } = await q.maybeSingle();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    if (!bug) return { content: [{ type: "text", text: "Bug not found" }], isError: true };
    const { data: comments } = await supabase.from("bug_comments").select("id, user_id, comment, created_at").eq("bug_id", bug.id).order("created_at");
    const { data: history } = await supabase.from("bug_history").select("field_changed, old_value, new_value, changed_by, changed_at").eq("bug_id", bug.id).order("changed_at");
    return jsonResult({ bug, comments: comments ?? [], history: history ?? [] });
  }
});

// src/lib/mcp/tools/list-timesheets.ts
import { defineTool as defineTool9 } from "npm:@lovable.dev/mcp-js@0.23.0";
import { z as z8 } from "npm:zod@^3.25.76";
var list_timesheets_default = defineTool9({
  name: "list_timesheets",
  title: "List timesheets",
  description: "Timesheet entries with bugs, content items, and summary text for a user + date range.",
  inputSchema: {
    project_id: z8.string().uuid(),
    from_date: z8.string(),
    to_date: z8.string(),
    user_id: z8.string().uuid().optional()
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ project_id, from_date, to_date, user_id }, ctx) => {
    const guard = await requireAdmin(ctx);
    if (!guard.ok) return guard.error;
    const supabase = getSupabaseForUser(ctx);
    let q = supabase.from("qa_timesheets").select("*").eq("project_id", project_id).gte("work_date", from_date).lte("work_date", to_date).order("work_date", { ascending: false });
    if (user_id) q = q.eq("user_id", user_id);
    const { data, error } = await q;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    const userIds = Array.from(new Set((data ?? []).map((t) => t.user_id)));
    const nameById = {};
    if (userIds.length) {
      const { data: profs } = await supabase.from("profiles").select("user_id, full_name, email").in("user_id", userIds);
      (profs ?? []).forEach((p) => nameById[p.user_id] = p.full_name || p.email);
    }
    const enriched = (data ?? []).map((t) => ({ ...t, user_name: nameById[t.user_id] ?? null }));
    return jsonResult({ timesheets: enriched });
  }
});

// src/lib/mcp/tools/list-testers.ts
import { defineTool as defineTool10 } from "npm:@lovable.dev/mcp-js@0.23.0";
import { z as z9 } from "npm:zod@^3.25.76";
var list_testers_default = defineTool10({
  name: "list_testers",
  title: "List testers",
  description: "List approved users in a project along with their role. Use this before assigning scenarios or flagging verdicts to pick the correct user_id.",
  inputSchema: {
    project_id: z9.string().uuid()
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ project_id }, ctx) => {
    const guard = await requireAdmin(ctx);
    if (!guard.ok) return guard.error;
    const supabase = getSupabaseForUser(ctx);
    const { data: access } = await supabase.from("user_project_access").select("user_id").eq("project_id", project_id);
    const ids = (access ?? []).map((a) => a.user_id);
    if (!ids.length) return jsonResult({ testers: [] });
    const { data: profs } = await supabase.from("profiles").select("user_id, full_name, email, approval_status").in("user_id", ids).eq("approval_status", "approved");
    const { data: roles } = await supabase.from("user_roles").select("user_id, role").in("user_id", ids);
    const roleById = {};
    (roles ?? []).forEach((r) => roleById[r.user_id] = r.role);
    const testers = (profs ?? []).map((p) => ({
      user_id: p.user_id,
      full_name: p.full_name,
      email: p.email,
      role: roleById[p.user_id] ?? "user"
    }));
    return jsonResult({ testers });
  }
});

// src/lib/mcp/tools/flag-verdict-for-retest.ts
import { defineTool as defineTool11 } from "npm:@lovable.dev/mcp-js@0.23.0";
import { z as z10 } from "npm:zod@^3.25.76";
var flag_verdict_for_retest_default = defineTool11({
  name: "flag_verdict_for_retest",
  title: "Flag verdict for re-test",
  description: "Mark a verdict as unsatisfactory and requiring re-test, with a reason. The tester sees this flag in their pending list. Pass verdict_id (preferred) OR (cycle_id + scenario_id + tester_id) to flag the latest verdict from that tester.",
  inputSchema: {
    verdict_id: z10.string().uuid().optional(),
    cycle_id: z10.string().uuid().optional(),
    scenario_id: z10.string().uuid().optional(),
    tester_id: z10.string().uuid().optional(),
    reason: z10.string().min(1).describe("Why this verdict needs re-test \u2014 shown to the tester.")
  },
  annotations: { readOnlyHint: false, destructiveHint: false, openWorldHint: false },
  handler: async (input, ctx) => {
    const guard = await requireAdmin(ctx);
    if (!guard.ok) return guard.error;
    const supabase = getSupabaseForUser(ctx);
    let verdictId = input.verdict_id;
    let cycleId = input.cycle_id;
    let scenarioId = input.scenario_id;
    let testerId = input.tester_id;
    if (!verdictId) {
      if (!cycleId || !scenarioId || !tester_id_present(input))
        return {
          content: [
            {
              type: "text",
              text: "Provide verdict_id OR all of cycle_id + scenario_id + tester_id."
            }
          ],
          isError: true
        };
      const { data: v } = await supabase.from("cycle_scenario_verdicts").select("id, cycle_id, scenario_id, user_id").eq("cycle_id", cycleId).eq("scenario_id", scenarioId).eq("user_id", testerId).order("created_at", { ascending: false }).limit(1).maybeSingle();
      if (!v)
        return { content: [{ type: "text", text: "No matching verdict found" }], isError: true };
      verdictId = v.id;
    } else {
      const { data: v } = await supabase.from("cycle_scenario_verdicts").select("id, cycle_id, scenario_id, user_id").eq("id", verdictId).maybeSingle();
      if (!v)
        return { content: [{ type: "text", text: "Verdict not found" }], isError: true };
      cycleId = v.cycle_id;
      scenarioId = v.scenario_id;
      testerId = v.user_id;
    }
    const { data, error } = await supabase.from("retest_flags").insert({
      verdict_id: verdictId,
      cycle_id: cycleId,
      scenario_id: scenarioId,
      tester_id: testerId,
      reason: input.reason,
      flagged_by: guard.userId
    }).select().maybeSingle();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    await supabase.from("cycle_scenario_comments").insert({
      cycle_id: cycleId,
      scenario_id: scenarioId,
      user_id: guard.userId,
      comment: `Flagged for re-test: ${input.reason}`
    });
    return jsonResult({ flag: data });
  }
});
function tester_id_present(input) {
  return !!input.tester_id;
}

// src/lib/mcp/tools/assign-scenarios.ts
import { defineTool as defineTool12 } from "npm:@lovable.dev/mcp-js@0.23.0";
import { z as z11 } from "npm:zod@^3.25.76";
var assign_scenarios_default = defineTool12({
  name: "assign_scenarios_to_tester",
  title: "Assign scenarios to tester",
  description: "Assign one or more cycle scenarios to a tester. Creates in-app notifications and shows up in the tester's pending list.",
  inputSchema: {
    cycle_id: z11.string().uuid(),
    scenario_ids: z11.array(z11.string().uuid()).min(1),
    assigned_to: z11.string().uuid(),
    note: z11.string().optional()
  },
  annotations: { readOnlyHint: false, destructiveHint: false, openWorldHint: false },
  handler: async ({ cycle_id, scenario_ids, assigned_to, note }, ctx) => {
    const guard = await requireAdmin(ctx);
    if (!guard.ok) return guard.error;
    const supabase = getSupabaseForUser(ctx);
    const rows = scenario_ids.map((sid) => ({
      cycle_id,
      scenario_id: sid,
      assigned_to,
      assigned_by: guard.userId,
      note: note ?? null
    }));
    const { data, error } = await supabase.from("scenario_assignments").upsert(rows, { onConflict: "cycle_id,scenario_id,assigned_to" }).select();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    const { data: cycle } = await supabase.from("test_cycles").select("cycle_code, name").eq("id", cycle_id).maybeSingle();
    await supabase.from("notifications").insert({
      user_id: assigned_to,
      type: "scenario_assignment",
      title: `${scenario_ids.length} scenario${scenario_ids.length === 1 ? "" : "s"} assigned to you`,
      message: cycle ? `In cycle ${cycle.cycle_code} \u2014 ${cycle.name}${note ? `: ${note}` : ""}` : note ?? "",
      metadata: { cycle_id, scenario_ids }
    });
    return jsonResult({ assigned: data?.length ?? 0, rows: data });
  }
});

// src/lib/mcp/tools/post-scenario-comment.ts
import { defineTool as defineTool13 } from "npm:@lovable.dev/mcp-js@0.23.0";
import { z as z12 } from "npm:zod@^3.25.76";
var post_scenario_comment_default = defineTool13({
  name: "post_scenario_comment",
  title: "Post scenario comment",
  description: "Add a comment to a scenario's discussion thread in a cycle. Attributed to the admin identity.",
  inputSchema: {
    cycle_id: z12.string().uuid(),
    scenario_id: z12.string().uuid(),
    comment: z12.string().min(1)
  },
  annotations: { readOnlyHint: false, destructiveHint: false, openWorldHint: false },
  handler: async ({ cycle_id, scenario_id, comment }, ctx) => {
    const guard = await requireAdmin(ctx);
    if (!guard.ok) return guard.error;
    const supabase = getSupabaseForUser(ctx);
    const { data, error } = await supabase.from("cycle_scenario_comments").insert({ cycle_id, scenario_id, user_id: guard.userId, comment }).select().maybeSingle();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return jsonResult({ comment: data });
  }
});

// src/lib/mcp/tools/create-cycle.ts
import { defineTool as defineTool14 } from "npm:@lovable.dev/mcp-js@0.23.0";
import { z as z13 } from "npm:zod@^3.25.76";
var create_cycle_default = defineTool14({
  name: "create_cycle",
  title: "Create test cycle with groups and scenarios",
  description: "Create a complete cycle in one call: cycle row + groups + scenarios. Use this after parsing a QA checklist. Scenario descriptions should follow the platform's standard format (What this is / What to try / Expected).",
  inputSchema: {
    project_id: z13.string().uuid(),
    name: z13.string().min(1),
    description: z13.string().optional(),
    priority: z13.enum(["critical", "high", "medium", "low"]).default("medium"),
    status: z13.enum(["draft", "active", "archived"]).default("draft"),
    groups: z13.array(
      z13.object({
        name: z13.string().min(1),
        description: z13.string().optional(),
        scenarios: z13.array(
          z13.object({
            scenario_code: z13.string().min(1),
            title: z13.string().min(1),
            description: z13.string().optional()
          })
        ).min(1)
      })
    ).min(1)
  },
  annotations: { readOnlyHint: false, destructiveHint: false, openWorldHint: false },
  handler: async (input, ctx) => {
    const guard = await requireAdmin(ctx);
    if (!guard.ok) return guard.error;
    const supabase = getSupabaseForUser(ctx);
    const { data: cycle, error: cErr } = await supabase.from("test_cycles").insert({
      project_id: input.project_id,
      name: input.name,
      description: input.description ?? null,
      priority: input.priority,
      status: input.status,
      created_by: guard.userId
    }).select().maybeSingle();
    if (cErr || !cycle)
      return {
        content: [{ type: "text", text: cErr?.message ?? "Cycle insert failed" }],
        isError: true
      };
    let groupIdx = 0;
    let totalScenarios = 0;
    for (const g of input.groups) {
      const { data: gRow, error: gErr } = await supabase.from("cycle_groups").insert({
        cycle_id: cycle.id,
        name: g.name,
        description: g.description ?? null,
        order_index: groupIdx++
      }).select().maybeSingle();
      if (gErr || !gRow)
        return { content: [{ type: "text", text: gErr?.message ?? "Group insert failed" }], isError: true };
      const scenarioRows = g.scenarios.map((s, i) => ({
        group_id: gRow.id,
        scenario_code: s.scenario_code,
        title: s.title,
        description: s.description ?? null,
        order_index: i,
        has_steps: false,
        steps: null
      }));
      const { error: sErr } = await supabase.from("cycle_scenarios").insert(scenarioRows);
      if (sErr) return { content: [{ type: "text", text: sErr.message }], isError: true };
      totalScenarios += scenarioRows.length;
    }
    return jsonResult({
      cycle,
      groups_created: input.groups.length,
      scenarios_created: totalScenarios
    });
  }
});

// src/lib/mcp/index.ts
var projectRef = "lysajjlxfgpbcsyaqjyu";
var mcp_default = defineMcp({
  name: "qa-platform-mcp",
  title: "QA Platform MCP",
  version: "0.1.0",
  instructions: [
    "Tools for managing the QA platform: read test cycles, verdicts, comments, bugs, and timesheets;",
    "flag weak verdicts for re-test; assign scenarios to testers; create new test cycles.",
    "All tools require the admin role. Start with list_projects to get a project_id.",
    "Judge verdict comment quality using the full comment text returned by get_scenario_verdicts."
  ].join(" "),
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [
    list_projects_default,
    list_cycles_default,
    get_cycle_default,
    get_scenario_verdicts_default,
    list_pending_scenarios_default,
    get_tester_activity_default,
    list_bugs_default,
    get_bug_default,
    list_timesheets_default,
    list_testers_default,
    flag_verdict_for_retest_default,
    assign_scenarios_default,
    post_scenario_comment_default,
    create_cycle_default
  ]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.23.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
